=== backbrace/backbrace/packages/backbrace-devkit/schema/pagemeta.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://schema.backbrace.io/pageMeta.json",
    "title": "Page meta data.",
    "type": "object",
    "properties": {
        "name": {
            "description": "Name of the page.",
            "type": "string"
        },
        "caption": {
            "description": "Caption of the page.",
            "type": "string"
        },
        "component": {
            "description": "Component for the whole page (defaults to `cardpage`).",
            "type": "string"
        },
        "controller": {
            "description": "Page controller.",
            "type": "string"
        },
        "tableName": {
            "description": "Name of the page's datasource.",
            "type": "string"
        },
        "icon": {
            "description": "Icon to use for the page.",
            "type": "string",
            "$ref": "icons.json"
        },
        "filters": {
            "description": "Filters for the page",
            "type": "string"
        },
        "sections": {
            "description": "Page sections.",
            "type": "array",
            "items": {
                "$ref": "#/definitions/pageSectionMeta"
            }
        }
    },
    "required": [
        "sections"
    ],
    "definitions": {
        "pageFieldMeta": {
            "description": "Page field meta data.",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the field.",
                    "type": "string"
                },
                "caption": {
                    "description": "Caption of the field.",
                    "type": "string"
                },
                "type": {
                    "description": "Data type for the field.",
                    "type": "string",
                    "$ref": "datatypes.json"
                },
                "component": {
                    "description": "Custom component to use for the field.",
                    "type": "string"
                },
                "width": {
                    "description": "Width of the field. Defaults to `100px`.",
                    "type": "string"
                },
                "hidden": {
                    "description": "Don't display the field on the page.",
                    "type": "boolean"
                },
                "editable": {
                    "description": "Readonly field.",
                    "type": "boolean"
                },
                "className": {
                    "description": "Classes to add to the field.",
                    "type": "string"
                }
            },
            "required": [
                "name"
            ]
        },
        "pageActionMeta": {
            "description": "Page action meta data.",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the action.",
                    "type": "string"
                },
                "text": {
                    "description": "Caption of the action.",
                    "type": "string"
                },
                "icon": {
                    "description": "Icon to use on the button.",
                    "type": "string",
                    "$ref": "icons.json"
                },
                "iconColor": {
                    "description": "Icon color. Defaults to header color.",
                    "type": "string"
                },
                "className": {
                    "description": "Classes to add to the button.",
                    "type": "string"
                }
            },
            "required": [
                "name"
            ]
        },
        "pageSectionMeta": {
            "description": "Page section meta data.",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the section.",
                    "type": "string"
                },
                "text": {
                    "description": "Caption of the section.",
                    "type": "string"
                },
                "pageName": {
                    "description": "Display a subpage in this section.",
                    "type": "string"
                },
                "icon": {
                    "description": "Section icon.",
                    "type": "string",
                    "$ref": "icons.json"
                },
                "className": {
                    "description": "Classes to add to the section.",
                    "type": "string"
                },
                "fields": {
                    "description": "Page section fields.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pageFieldMeta"
                    }
                },
                "actions": {
                    "description": "Page actions.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pageActionMeta"
                    }
                }
            },
            "required": [
                "name"
            ]
        }
    }
}

=== backbrace/backbrace/packages/backbrace-docs/src/meta/page/apihome.json
{
    "$schema": "../../../node_modules/@backbrace/devkit/schema/pagemeta.json",
    "name": "API List",
    "tableName": "table/modules",
    "component": "templatepage",
    "controller": "controllers/apihome.js",
    "sections": [
        {
            "name": "footer",
            "pageName": "page/footer"
        }
    ]
}

=== backbrace/backbrace/packages/backbrace-docs/src/meta/page/guide.json
{
    "$schema": "../../../node_modules/@backbrace/devkit/schema/pagemeta.json",
    "name": "index",
    "tableName": "table/tutorials",
    "component": "templatepage",
    "controller": "controllers/guide.js",
    "sections": [
        {
            "name": "footer",
            "pageName": "page/footer"
        }
    ]
}

=== backbrace/backbrace/packages/backbrace-docs/src/design/page/components/editorpage.json
{
    "$schema": "../../../../../backbrace-devkit/schema/pagedesign.json",
    "name": "editorpage",
    "caption": "EditorPage Component",
    "controller": "page/components/component.js",
    "sections": [
        {
            "name": "Title",
            "component": "templatepage",
            "options": {
                "template": "<p>The editorpage component is used to display and allow the user to edit code. It supports many languages ie. Javascript, JSON</p>"
            }
        },
        {
            "name": "Javascript Editor",
            "component": "editorpage",
            "options": {
                "file": "/design/page/components/component.js"
            }
        },
        {
            "name": "Javascript Editor Source",
            "text": "Source",
            "component": "templatepage",
            "options": {
                "useWindowComponent": true
            }
        },
        {
            "name": "JSON Desc",
            "component": "templatepage",
            "options": {
                "template": "<p class='desc'>By default, the editorpage uses <code>javascript</code> mode but the <code>type</code> option can be used to load other languages.</p>"
            }
        },
        {
            "name": "JSON Editor",
            "component": "editorpage",
            "options": {
                "type": "json",
                "file": "/design/page/components/editorpage.json"
            }
        },
        {
            "name": "JSON Editor Source",
            "text": "Source",
            "component": "templatepage",
            "options": {
                "useWindowComponent": true
            }
        },
        {
            "name": "footer",
            "component": "templatepage",
            "data": "design/data/tutorials.json",
            "controller": "page/footer.js"
        }
    ]
}

=== backbrace/backbrace/packages/backbrace-docs/src/design/page/components/textfield.json
{
    "$schema": "../../../../../backbrace-devkit/schema/pagedesign.json",
    "name": "textfield",
    "caption": "TextField Component",
    "controller": "page/components/component.js",
    "sections": [
        {
            "name": "Title",
            "component": "templatepage",
            "options": {
                "template": "<p>Text fields are a common feature in most user interfaces. It can be initially or programmatically disabled.</p>"
            }
        },
        {
            "name": "States",
            "className": "col-md-6",
            "fields": [
                {
                    "name": "Normal"
                },
                {
                    "name": "Disabled",
                    "editable": false
                }
            ]
        },
        {
            "name": "States Source",
            "text": "Source",
            "className": "col-md-6",
            "component": "templatepage",
            "options": {
                "useWindowComponent": true
            }
        },
        {
            "name": "Types Desc",
            "component": "templatepage",
            "options": {
                "template": "<p class='desc'>Text fields can be also used to validate different types of values.</p>"
            }
        },
        {
            "name": "Types",
            "className": "col-md-6",
            "fields": [
                {
                    "name": "Email"
                },
                {
                    "name": "Money"
                },
                {
                    "name": "Password"
                }
            ]
        },
        {
            "name": "Types Source",
            "text": "Source",
            "className": "col-md-6",
            "component": "templatepage",
            "options": {
                "useWindowComponent": true
            }
        },
        {
            "name": "Data Desc",
            "component": "templatepage",
            "options": {
                "template": "<p class='desc'>Data can be loaded into a textfield by using the <code>dataName</code> property.</p>"
            }
        },
        {
            "name": "Data",
            "className": "col-md-6",
            "data": "design/data/sample.json",
            "fields": [
                {
                    "name": "String",
                    "dataName": "string"
                }
            ]
        },
        {
            "name": "Data Source",
            "text": "Source",
            "className": "col-md-6",
            "component": "templatepage",
            "options": {
                "useWindowComponent": true
            }
        },
        {
            "name": "footer",
            "component": "templatepage",
            "data": "design/data/tutorials.json",
            "controller": "page/footer.js"
        }
    ]
}

=== backbrace/backbrace/packages/backbrace-sample-app/meta/page/test.json
{
    "$schema": "../../node_modules/@backbrace/devkit/schema/pagemeta.json",
    "name": "test",
    "controller": "page/test.js",
    "caption": "Test Page",
    "icon": "account",
    "sections": [
        {
            "name": "General",
            "fields": [
                {
                    "name": "First Name",
                    "type": "Text"
                },
                {
                    "name": "Last Name",
                    "type": "Text"
                }
            ],
            "actions": [
                {
                    "name": "Code",
                    "icon": "language-javascript"
                },
                {
                    "name": "Save Page",
                    "icon": "check"
                }
            ]
        },
        {
            "name": "Stuff",
            "icon": "account",
            "className": "s12 m6",
            "fields": [
                {
                    "name": "Account #",
                    "type": "Text"
                }
            ]
        },
        {
            "name": "Junk",
            "icon": "trash-can",
            "className": "s12 m6"
        }
    ]
}
